# Generated by Django 3.2.15 on 2022-08-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('seq', models.AutoField(db_column='SEQ', primary_key=True, serialize=False)),
                ('journal_id', models.CharField(db_column='JOURNAL_ID', max_length=10)),
                ('title', models.CharField(db_column='TITLE', max_length=200)),
                ('publish_date', models.CharField(blank=True, db_column='PUBLISH_DATE', max_length=20, null=True)),
                ('link_url', models.CharField(blank=True, db_column='LINK_URL', max_length=200, null=True)),
                ('writer', models.CharField(blank=True, db_column='WRITER', max_length=50, null=True)),
                ('content', models.TextField(blank=True, db_column='CONTENT', null=True)),
                ('reg_date', models.DateTimeField(db_column='REG_DATE')),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField(db_column='EMPNO')),
                ('sal', models.IntegerField(db_column='SAL')),
            ],
            options={
                'db_table': 'SALARY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(db_column='NO')),
                ('name', models.CharField(db_column='NAME', max_length=10)),
                ('score', models.IntegerField(db_column='SCORE')),
                ('subject', models.CharField(db_column='SUBJECT', max_length=20)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=20, null=True)),
            ],
            options={
                'db_table': 'STUDENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(db_column='NO')),
                ('name', models.CharField(db_column='NAME', max_length=10)),
                ('grade', models.IntegerField(db_column='GRADE')),
                ('subject', models.CharField(db_column='SUBJECT', max_length=20)),
                ('score', models.IntegerField(db_column='SCORE')),
                ('phone', models.CharField(db_column='PHONE', max_length=20)),
            ],
            options={
                'db_table': 'STUDENT2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid', models.IntegerField(db_column='STID')),
                ('name', models.CharField(db_column='NAME', max_length=10)),
                ('score', models.IntegerField(db_column='SCORE')),
                ('deptid', models.IntegerField(db_column='DEPTID')),
            ],
            options={
                'db_table': 'STUDENT3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(db_column='CODE')),
                ('name', models.CharField(db_column='NAME', max_length=10)),
                ('grade', models.CharField(db_column='GRADE', max_length=2)),
                ('score', models.IntegerField(db_column='SCORE')),
            ],
            options={
                'db_table': 'SUBJECT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='CODE', max_length=4)),
                ('name', models.CharField(db_column='NAME', max_length=10)),
            ],
            options={
                'db_table': 'T1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(db_column='NO', max_length=2)),
                ('rule', models.CharField(db_column='RULE', max_length=10)),
            ],
            options={
                'db_table': 'T2',
                'managed': False,
            },
        ),
    ]
